controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
list_events:
  path: /api/list
  controller: App\Controller\ApiEvenementController::afficher

